In [17]:
import sqlite3
import pandas as pd

In [18]:
#connect to DB
conn = sqlite3.connect('datawarehouse.db')
cursor = conn.cursor()
print("Opened database successfully");

Opened database successfully


# Analyse


Um unsere Forschungsfrage durchzuführen wird in diesem Notebook die Analyse durchgeführt. Weitere Informationen über die Forschungsfrage und unsere Dokumentation ist in unserem [Wiki](https://github.com/Fuenfgeld/DMA2022DataProjectA/wiki) zu finden.

Die folgende Query liefert und alle Patienten, die gegen Influenza geimpft wurden. Die Impfung mit dem Code 140 ist die Influenzaimpfung in unserem Datensatz

In [20]:
print(pd.read_sql_query("SELECT DISTINCT patient_ID, VALUE FROM facts_table WHERE immunization_code is NOT NULL AND VALUE==140", conn))

                                patient_ID  VALUE
0     7f30313f-98e9-2cc2-68a5-6f9973f9ad5a    140
1     2f114e21-8b95-e9eb-2e9e-4b950b059cfa    140
2     f7dddcba-380e-7fd4-20b0-da086ce5dc3a    140
3     ad5525c0-fdab-94dc-018f-d7209c72bdef    140
4     2812f4fc-6aba-0033-728b-7e569bb8adcc    140
...                                    ...    ...
1045  edab2899-dac4-a19d-59e2-a9bea7b95cab    140
1046  d1065043-2a5f-2d0e-1dd0-cb7f31e6d340    140
1047  4c523ab1-3255-911a-7eef-3bc3e48b7b05    140
1048  8d49cb05-b1c3-b8fe-dc75-e43ad861f074    140
1049  fce5ed5c-e218-4839-a0c5-6ef906e5ae73    140

[1050 rows x 2 columns]


Die folgende Query liefert und alle Patienten, die gegen Influenza geimpft wurden. Jeder Patient der als VALUE "COVID-19" hat, ist an Covid-19 gestorben. Nach unserer Definition gilt ein Verlauf als schwer, wenn der Patient stirbt.

In [32]:
print(pd.read_sql_query("SELECT DISTINCT patient_ID, VALUE FROM facts_table WHERE observation_code is NOT NULL AND VALUE=='COVID-19'", conn))

                              patient_ID     VALUE
0   20604c29-ee90-6073-13f4-df3678392fc7  COVID-19
1   bec7fd7c-d645-1450-f851-e21e07c2a442  COVID-19
2   6a59c578-ebb4-e0bb-0b82-d5c57d5e9f2a  COVID-19
3   d4ec20ef-1ed3-9d97-36c5-1216c4037f05  COVID-19
4   adcc96d4-285a-e833-f968-13a940c78098  COVID-19
5   cbcf9807-abfa-0ae8-7f3d-ac05fb0e61f5  COVID-19
6   92df158a-bcb4-01af-1529-adf33db69253  COVID-19
7   b228751b-8384-9070-a49c-faa67070f494  COVID-19
8   63576001-7584-d85a-e056-475fe720a291  COVID-19
9   69ba11d9-8061-f328-0733-ab332742c586  COVID-19
10  68a2bbc6-3f56-081e-3fd5-cbd13248ed31  COVID-19
11  b56193a1-5bfb-bb37-0886-9a02d10edd41  COVID-19
12  cc43826f-49e1-1144-76d4-464f992c9dd0  COVID-19
13  8a84c9b4-0ee2-8cd0-a78b-ed8e8d654467  COVID-19
14  de5013bd-4eb1-8e08-e863-c0ee3a03d6ca  COVID-19
15  15905260-4510-3a9a-53b3-88a440c2128d  COVID-19
16  26d353df-e9af-35b0-b694-af604d610bd9  COVID-19
17  212b3d3b-eb3c-cb51-b0fe-08554b71ac2a  COVID-19
18  12f8384e-d49a-1343-2e3a-dc5

In [22]:
#alle Patienten die Corona oder verdacht auf Corona haben
#print(pd.read_sql_query("SELECT DISTINCT patient_ID, VALUE FROM facts_table WHERE condition_Id is NOT NULL AND (VALUE==840539006 OR VALUE==840544004)", conn))


                                patient_ID      VALUE
0     ad5525c0-fdab-94dc-018f-d7209c72bdef  840544004
1     ad5525c0-fdab-94dc-018f-d7209c72bdef  840539006
2     7f30313f-98e9-2cc2-68a5-6f9973f9ad5a  840544004
3     7f30313f-98e9-2cc2-68a5-6f9973f9ad5a  840539006
4     2812f4fc-6aba-0033-728b-7e569bb8adcc  840544004
...                                    ...        ...
1765  edab2899-dac4-a19d-59e2-a9bea7b95cab  840539006
1766  4c523ab1-3255-911a-7eef-3bc3e48b7b05  840544004
1767  4c523ab1-3255-911a-7eef-3bc3e48b7b05  840539006
1768  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840544004
1769  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006

[1770 rows x 2 columns]


In [23]:
#selbe wie drüber + Symptome, brauchen wir nicht mehr wenn wir schwerer verlauf als patient tot definieren
#print(pd.read_sql_query("SELECT DISTINCT patient_ID, facts_table.VALUE, conditions.DESCRIPTION FROM facts_table LEFT JOIN conditions ON facts_table.patient_ID = conditions.PATIENT LEFT JOIN immunizations ON facts_table.patient_ID = immunizations.PATIENT LEFT JOIN observations ON facts_table.patient_ID = observations.PATIENT WHERE facts_table.condition_Id is NOT NULL AND (facts_table.VALUE==840539006 OR facts_table.VALUE==840544004) AND observations.VALUE=='COVID-19' AND immunizations.CODE==140", conn))


                               patient_ID      VALUE  \
0    20604c29-ee90-6073-13f4-df3678392fc7  840544004   
1    20604c29-ee90-6073-13f4-df3678392fc7  840544004   
2    20604c29-ee90-6073-13f4-df3678392fc7  840544004   
3    20604c29-ee90-6073-13f4-df3678392fc7  840544004   
4    20604c29-ee90-6073-13f4-df3678392fc7  840544004   
..                                    ...        ...   
789  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006   
790  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006   
791  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006   
792  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006   
793  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006   

                                        DESCRIPTION  
0               Acute pulmonary embolism (disorder)  
1    Acute respiratory distress syndrome (disorder)  
2              Acute respiratory failure (disorder)  
3           Bacterial infectious disease (disorder)  
4                                          COVID-19  
.. 

In [24]:
#df_nur_influenza_geimpfte = pd.read_sql_query("SELECT DISTINCT patient_ID, facts_table.VALUE, conditions.DESCRIPTION AS Condition_Description, immunizations.CODE, observations.DESCRIPTION AS Observation_Description FROM facts_table LEFT JOIN conditions ON facts_table.patient_ID = conditions.PATIENT LEFT JOIN immunizations ON facts_table.patient_ID = immunizations.PATIENT LEFT JOIN observations ON facts_table.patient_ID = observations.PATIENT WHERE facts_table.condition_Id is NOT NULL AND (facts_table.VALUE==840539006 OR facts_table.VALUE==840544004) AND immunizations.CODE==140", conn)


In [25]:
#df_nur_influenza_geimpfte

patient_ID      VALUE Condition_Description  \
0       7f30313f-98e9-2cc2-68a5-6f9973f9ad5a  840544004              COVID-19   
1       7f30313f-98e9-2cc2-68a5-6f9973f9ad5a  840544004              COVID-19   
2       7f30313f-98e9-2cc2-68a5-6f9973f9ad5a  840544004              COVID-19   
3       7f30313f-98e9-2cc2-68a5-6f9973f9ad5a  840544004              COVID-19   
4       7f30313f-98e9-2cc2-68a5-6f9973f9ad5a  840544004              COVID-19   
...                                      ...        ...                   ...   
325412  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006    Suspected COVID-19   
325413  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006    Suspected COVID-19   
325414  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006    Suspected COVID-19   
325415  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006    Suspected COVID-19   
325416  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006    Suspected COVID-19   

        CODE                            Observation_Description  
0        140                                        Body Weight  
1        140                                   Body temperature  
2        140                                               DALY  
3        140                           Diastolic Blood Pressure  
4        140                                         Heart rate  
...      ...                                                ...  
325412   140           Sodium [Moles/volume] in Serum or Plasma  
325413   140                            Systolic Blood Pressure  
325414   140  Troponin I.cardiac [Mass/volume] in Serum or P...  
325415   140     Urea nitrogen [Mass/volume] in Serum or Plasma  
325416   140                               pH of Arterial blood  

[325417 rows x 5 columns]

### Wie viele gestorbene waren gegen Influenza geimpft?

VALUE=840539006 und VALUE=840544004 bedeuten Suspected COVID-19 und COVID-19

In [26]:
df_alle_patienten_infos = pd.read_sql_query("SELECT patient_ID, facts_table.VALUE, conditions.DESCRIPTION AS Condition_Description, immunizations.CODE, observations.DESCRIPTION AS Observation_Description FROM facts_table LEFT JOIN conditions ON facts_table.patient_ID = conditions.PATIENT LEFT JOIN immunizations ON facts_table.patient_ID = immunizations.PATIENT LEFT JOIN observations ON facts_table.patient_ID = observations.PATIENT WHERE facts_table.condition_Id is NOT NULL AND (facts_table.VALUE==840539006 OR facts_table.VALUE==840544004) AND observations.VALUE=='COVID-19'", conn)

Aufbau des Dataframes

In [27]:
df_alle_patienten_infos.tail()

patient_ID      VALUE Condition_Description  \
8413  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006    Suspected COVID-19   
8414  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006    Suspected COVID-19   
8415  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006    Suspected COVID-19   
8416  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006    Suspected COVID-19   
8417  8d49cb05-b1c3-b8fe-dc75-e43ad861f074  840539006    Suspected COVID-19   

      CODE                            Observation_Description  
8413   140  Cause of Death [US Standard Certificate of Death]  
8414   140  Cause of Death [US Standard Certificate of Death]  
8415   140  Cause of Death [US Standard Certificate of Death]  
8416   140  Cause of Death [US Standard Certificate of Death]  
8417   140  Cause of Death [US Standard Certificate of Death]

Hier werden alle gestorbenen Patienten durchsucht, haben sie eine Influenzaimpfung erhalten, werden sie mit TRUE markiert.

In [28]:
impfkandidat = []
geimpfte_patienten_df = pd.DataFrame(columns=['Patienten', 'Grippe Impfung'])
geimpfte_patienten_df.Patienten = df_alle_patienten_infos.patient_ID.unique()

#Prüfung ob der Code 140 in den Daten enthalten ist, dieser gibt Aufschluss darauf ob die Patienten eine Grippeimpfung erhalten haben. 
for id in df_alle_patienten_infos.patient_ID.unique():
    patient = df_alle_patienten_infos.loc[df_alle_patienten_infos.patient_ID == id]
    exist = 140 in patient['CODE'].unique()
    impfkandidat.append(exist)
geimpfte_patienten_df['Grippe Impfung']= impfkandidat
geimpfte_patienten_df

Patienten  Grippe Impfung
0   20604c29-ee90-6073-13f4-df3678392fc7            True
1   bec7fd7c-d645-1450-f851-e21e07c2a442            True
2   6a59c578-ebb4-e0bb-0b82-d5c57d5e9f2a            True
3   d4ec20ef-1ed3-9d97-36c5-1216c4037f05            True
4   adcc96d4-285a-e833-f968-13a940c78098            True
5   cbcf9807-abfa-0ae8-7f3d-ac05fb0e61f5            True
6   92df158a-bcb4-01af-1529-adf33db69253            True
7   b228751b-8384-9070-a49c-faa67070f494            True
8   63576001-7584-d85a-e056-475fe720a291            True
9   69ba11d9-8061-f328-0733-ab332742c586            True
10  68a2bbc6-3f56-081e-3fd5-cbd13248ed31            True
11  b56193a1-5bfb-bb37-0886-9a02d10edd41            True
12  cc43826f-49e1-1144-76d4-464f992c9dd0            True
13  8a84c9b4-0ee2-8cd0-a78b-ed8e8d654467            True
14  de5013bd-4eb1-8e08-e863-c0ee3a03d6ca            True
15  15905260-4510-3a9a-53b3-88a440c2128d            True
16  26d353df-e9af-35b0-b694-af604d610bd9            True
17  212b3d3b-eb3c-cb51-b0fe-08554b71ac2a            True
18  12f8384e-d49a-1343-2e3a-dc547629d770            True
19  ac1c63de-5c72-a482-4d1a-3cea500dba3f            True
20  3845c8f4-39c6-eeec-75e6-2780169f0aa3            True
21  27d46fed-1591-5a1f-b92c-667e495e6b1c            True
22  6008a677-9edd-5ffc-699f-c32a109ffabd            True
23  8d49cb05-b1c3-b8fe-dc75-e43ad861f074            True

In [29]:
conn.close()